### ISSUE TITLE
Compiling not possible - cpu-feature.h not found

### ISSUE THREAD

**Issue by acocalypso** [SachinVin/citra_android#41] opened 2018-10-14 14:21 UTC
I checked out the frontend and backend and wanted to give it a try.

But after Setting up and generated the gradle - the build is not possible as cpu-feature.h is not found.

Is there a missing commit?

full log:
https://pastebin.com/B0FBJd8T

After chaning the cpu.cpp to fullpath compiling is possible.

Setting an env variable ANDROID_ROOT_NDK did not solve the issue.

Windows 10

```
// The cpu-features header and source file are located in $ANDROID_NDK_ROOT/sources/android/cpufeatures
// setenv-android.sh will copy the header and source file into PWD and the makefile will build it in place.
#if defined(__ANDROID__)
# include "C:\Users\Aco\AppData\Local\Android\Sdk\ndk-bundle\sources\android\cpufeatures\cpu-features.h"
#endif
```

**Comment by acocalypso** [comment] 2018-10-14 17:04
Didn't checked that the file should be loaded from $ANDROID_NDK_ROOT which is not part of my environment variables.

**Comment by mascondante** [comment] 2018-10-15 01:31
Same issue. Looking over the log the error is here: 
`citra/externals/cryptopp/cryptopp/cpu.cpp:49:11: fatal error: 'cpu-features.h' file not found`

The issue isn't a missing commit from what [I'm reading](https://stackoverflow.com/questions/41554511/how-to-add-cpufeatures-to-android-jni-cmake-gradle-build). That article suggests a couple minor changes in CMakeLists.txt should resolve things. I'm just not sure what to put for the target in `target_link_libraries(<your target>, cpufeatures)` part of the solution referenced in the above linked article.

**Comment by mascondante** [comment] 2018-10-15 15:55
Okay so my fresh install of cmake was missing [AndroidNdkModules.cmake](https://github.com/taka-no-me/android-cmake/blob/master/AndroidNdkModules.cmake). I discovered this by editing `citra\externals\cryptopp\CMakeLists.txt` to include:

`include(AndroidNdkModules)
android_ndk_import_module_cpufeatures()
target_link_libraries(cryptopp cpufeatures)`

This was added to the bottom of the file under Third-party libraries. I'm still building but I wanted to get this info out before I forgot what I did. I'm sure there's a far more efficient place to put the NDK includes like perhaps in the top CMakeLists.txt file but as I've indicated I'm no developer. Just trying to band-aid a solution together to make life easier on the actual dev so he doesn't have to spend so much time figuring things out.

**Comment by SachinVin** [comment] 2018-10-15 16:14
@mascondante does this actually work? even i was looking for an easier solution.
Cryptopp relies on its `setenv-android.sh` for copying `cpu-features.cpp/.h` to the folder, this works on linux...but since windows doesn't support `.sh` you manually have to copy the files

**Comment by mascondante** [comment] 2018-10-15 16:31
@SachinVin It built the APK. The APK runs but when I add a game to the library it crashes and will keep crashing every time I try to open it unless I clear the app data.

**Comment by SachinVin** [comment] 2018-10-15 16:44
@mascondante I'm gonna take a wild guess and say it's because of `+=`  that stupidly missed.
It's should be fixed now

**Comment by mascondante** [comment] 2018-10-15 17:00
@SachinVin Sorry I was just filtering a logcat for you. I'll try your update. In the meantime here's the [logcat](https://pastebin.com/pDdGQ1Qe)

**Comment by mascondante** [comment] 2018-10-15 18:52
@SachinVin No go. Same result. Tried renaming the game to something simple in case that had something to do with things. Didn't help. I tried debugging it with my phone but I don't really know what I'm doing. I'm in the Citra discord if you want to hit me up there. Would be quicker. They tagged you but you appear to be offline there. I'm @mascondante#8038

**Comment by acocalypso** [comment] 2018-10-15 20:28
@SachinVin  after your last commit - running a game is possible now. But for some reasons the FPS is only 1/4 of the build from august.

**Closed** 2018-10-19 12:55 UTC
