### ISSUE TITLE
System clock

### ISSUE THREAD

**Issue by Yodakiller3000** [SachinVin/citra_android#167] opened 2019-01-18 23:02 UTC
I tryed using the system clock in multiple games but it's stuck on January 1st 2012. I've played Pokemon Sun and also Animal Crossing New Leaf. This is probably going to be a really important bug too fix.

**Comment by EnergyCube** [comment] 2019-01-19 14:05
The problem is fixed on the version of PlayStore I think.
Check settings

**Comment by HelloOO7** [comment] 2019-01-20 15:45
Are you using the CI build from https://ci.appveyor.com/project/SachinVin/citra-android/build/artifacts ? I fixed that issue months ago. Just checked and it still does what it should do - change the config file accordingly. Check your settings, system clock type in particular. If it's "Simulated Clock", then it's using the fallback fixed time mode. Change it to device clock and it should use the time currently set in your OS.

**Closed as completed** 2019-01-30 16:05 UTC
